# 参考 https://docs.min.io/docs/minio-docker-quickstart-guide.html
services:
  minio:
    image: minio/minio:latest                         # 镜像
    container_name: minio                             # 容器名
    restart: unless-stopped                           # 重启策略
    volumes:                                          # 数据卷挂载
      - "$HOME/docker/minio/data:/data"
      - "$HOME/docker/minio/minio:/minio"
      - "$HOME/docker/minio/config:/root/.minio"
    environment:                                      # 设置环境变量
      TZ: Asia/Shanghai                               # 设置时区
      LANG: en_US.UTF-8                               # 设置语言
      MINIO_ACCESS_KEY: "root"                        # 登录账号
      MINIO_SECRET_KEY: "password"                    # 登录密码
      MINIO_SERVER_URL: "https://minio.example.com" # 服务网址
      MINIO_BROWSER_REDIRECT_URL: "https://console.minio.example.com" # console网址
    command: server /data  --console-address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:                              # 映射端口
      - "9000:9000"
      - "9001:9001"